# Generated by Django 3.2.3 on 2021-05-30 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('idCapacitacion', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Capacitacion')),
                ('nombreCapa', models.CharField(max_length=50, verbose_name='Nombre Capacitacion')),
                ('descripcion', models.CharField(max_length=400, verbose_name='Descripcion Capacitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut Cliente')),
                ('nombreCli', models.CharField(max_length=100, verbose_name='Nombre Cliente')),
                ('apellidoCli', models.CharField(max_length=100, verbose_name='Apellido Cliente')),
                ('correoCli', models.CharField(max_length=150, verbose_name='Correo Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Asesoria',
            fields=[
                ('idTipo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Tipo Asesoria')),
                ('nombreTipo', models.CharField(max_length=50, verbose_name='Nombre Tipo Asesoria')),
            ],
        ),
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('idAsesoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de asesoria')),
                ('nombreAsesoria', models.CharField(max_length=50, verbose_name='Nombre de la asesoria')),
                ('descrpcion', models.CharField(max_length=400, verbose_name='Descripcion Asesoria')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.tipo_asesoria')),
            ],
        ),
    ]
