# Generated by Django 3.2.3 on 2021-05-30 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asesoria',
            old_name='categoria',
            new_name='Tipo_Asesoria',
        ),
    ]
