# Generated by Django 3.2.3 on 2021-06-05 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_rename_categoria_asesoria_tipo_asesoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idServicio', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Servicio')),
                ('nombreServicio', models.CharField(max_length=50, verbose_name='Nombre Servicio')),
                ('descrpcion', models.CharField(max_length=400, verbose_name='Descripcion Servicio')),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosContratados',
            fields=[
                ('idServicioContr', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Servicio Contratado')),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('idTipo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Tipo Servicio')),
                ('nombreTipo', models.CharField(max_length=50, verbose_name='Nombre Tipo Servicio')),
            ],
        ),
        migrations.RemoveField(
            model_name='asesoria',
            name='Tipo_Asesoria',
        ),
        migrations.DeleteModel(
            name='Capacitacion',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellidoCli',
            field=models.CharField(max_length=30, verbose_name='Apellido Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombreCli',
            field=models.CharField(max_length=20, verbose_name='Nombre Cliente'),
        ),
        migrations.DeleteModel(
            name='Asesoria',
        ),
        migrations.DeleteModel(
            name='Tipo_Asesoria',
        ),
        migrations.AddField(
            model_name='servicioscontratados',
            name='Cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.cliente'),
        ),
        migrations.AddField(
            model_name='servicioscontratados',
            name='Servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='TipoServicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.tiposervicio'),
        ),
    ]
