# Generated by Django 3.2.3 on 2021-06-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_auto_20210606_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='imgServicio',
            field=models.ImageField(null=True, upload_to='IMGS', verbose_name='Imagen del Servicio'),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='imgTipo',
            field=models.ImageField(null=True, upload_to='IMGTS', verbose_name='Imagen del Tipo Servicio'),
        ),
    ]
