# Generated by Django 3.2.3 on 2021-06-13 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_auto_20210606_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicioscontratados',
            name='Cliente',
        ),
        migrations.RemoveField(
            model_name='servicioscontratados',
            name='Servicio',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='ServiciosContratados',
        ),
    ]
